name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on:
  push:
    branches: [ main ]
jobs:
  refresh-cdn:
    runs-on: ubuntu-latest
    container:
      image: node:14.16
    steps:
      - name: Check for dockerenv file
        run: (ls /.dockerenv && echo Found dockerenv) || (echo No dockerenv)

